MKSHELL=/bin/bash
#Definir MKSHELL ahora debe ir siempre arriba con /bin/bash. "Todo lo que viene a continuación interprétalo con bash"

#Este módulo comprime los archivos VCFs
%.sorted.normalized.split_multiallelics.vcf.gz:Q: %.vcf
	echo "[DEBUG] Comprimiendo archivos para $prereq"
	bcftools norm \
		--fasta-ref $GENOME_REFERENCE \
		--multiallelics -any \
		$prereq \
	| bcftools sort \
	| uniq \
	| bgzip > $target 
