MKSHELL=/bin/bash
#Definir MKSHELL ahora debe ir siempre arriba con /bin/bash. "Todo lo que viene a continuación interprétalo con bash"

#Este bloque simplifica el vcf con bcftools para hacerlo más fácilmente manipulable
%.header.vcf.gz:Q: %.vcf.gz
	echo "[DEBUG] Añadiendo contigs al encabezado"
	$BCFTOOLS annotate \
		--header-lines header_lines.txt \
		$prereq \
	| bgzip > $target
